apiVersion: v1
kind: Service
metadata:
  name: lembretes-service
spec:
  selector:
    app: lembretes
  ports:
    - protocol: TCP
      port: 9000              # Porta pela qual o serviço será acessado dentro do cluster
      targetPort: 9000         # Porta exposta pelo contêiner no deployment
  type: ClusterIP
