apiVersion: v1
kind: Service
metadata:
  name: consulta-service
spec:
  selector:
    app: consulta
  ports:
    - protocol: TCP
      port: 5000            # Porta pela qual o serviço será acessado dentro do cluster
      targetPort: 5000       # Porta exposta pelo contêiner no deployment
  type: ClusterIP
