version: '3.8'

services:
  consulta:
    build:
      context: .  
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5000:5000"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
