apiVersion: v1
kind: Service
metadata:
  name: tti301-lembretes-service
spec:
  type: NodePort
  selector:
    app: tti301-lembretes
  ports:
    - name: tti301-lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000