version: '3.8'

services:
  observacoes:
    build:
      context: .  # Contexto atual do serviço
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "7000:7000"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
