apiVersion: v1
kind: Service
metadata:
  name: observacoes-service
spec:
  selector:
    app: observacoes
  ports:
    - protocol: TCP
      port: 7000               # Porta pela qual o serviço será acessado dentro do cluster
      targetPort: 7000         # Porta exposta pelo contêiner no deployment
  type: ClusterIP
